version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
      - ENV=production
    command: >
      sh -c "uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload"