name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Run tests
      run: |
        pytest tests/ --junitxml=test-results.xml -v
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.xml

  build-and-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t penguin-classifier .
      
    - name: Test container
      run: |
        docker run -d -p 8000:8000 --name penguin-app penguin-classifier

        for i in {1..12}; do
          if docker logs penguin-app 2>&1 | grep -q "Application startup complete"; then
            break
          fi
          sleep 10
        done

        curl -sSf http://localhost:8000/health || exit 1

        curl -sSf -X POST http://localhost:8000/predict \
          -H "Content-Type: application/json" \
          -d '{"island":"Torgersen","culmen_length_mm":39.1,"culmen_depth_mm":18.7,"flipper_length_mm":181.0,"body_mass_g":3750.0,"sex":"MALE"}' \
          | grep -q '"species":' || exit 1